sampler: ddpm
steps: 1000
noise_schedule: linear
model_mean_type: epsilon  # Mean type is epsilon, posterior mean is calculated using q_posterior_mean function. Don't need to compute x_start, just need q_posterior_mean
model_var_type: learned_range
dynamic_threshold: False
clip_denoised: True
rescale_timesteps: False
timestep_respacing: 1000
