dpsconditioning:
  method: ps
  params:
    scale: 1.0

tmpdconditioning:
  method: tmp

pigdmconditioning:
  method: pig

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: motion_blur
    kernel_size: 61
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.1
