dpsconditioning:
  method: ps
  params:
    scale: 1.0

tmpdconditioning:
  method: tmp

pigdmconditioning:
  method: pig

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0

  noise: 
    name: gaussian
    sigma: 0.01
